name: CD

on:
  push:
    branches:
      - master
      - 'feature/**'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: GOOS=linux go build -o pensiondata-api gihtub.com/obawi/pensiondata-api/cmd/api

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pensiondata-api
          path: pensiondata-api